expression/collections/seq.py, expression/core/aiotools.py, expression/core/option.py
`Option.to_seq() -> Seq` requires some `if TYPE_CHECKING` and deferred import hacks to avoid circular dependencies. What do you think?
=> Make Option.to_seq() return a Seq and add .of classmethods to Seq

expression/collections/frozenlist.py, expression/collections/seq.py, expression/core/match.py, tests/test_match.py
- Fix match by not binding pattern to generic type of Case class. We still need the generic type of the Case class for default handling etc. 
- Add empty static constructors for seq and frozenlist.
Without this fix, `x` below will show type as `Type[List[int]]` and not `List[int]`:
```python
xs = [1, 2, 3]
with match(xs) as case:
for x in case(List[int]):
assert x == xs
```
=> Fix match of generic type

.pre-commit-config.yaml, expression/core/result.py, tests/test_result.py
- Fix typing bug in Result. Should be Iterable of TSource only
- Add generic types to Result match to infer the value / error correctly
=> Update to pyright 1.1.98

expression/extra/result/__init__.py, expression/extra/result/catch.py, tests/test_catch.py
Implements the utility decorator `catch` per the discussion in #5.
=> Implement the catch utility decorator

.pre-commit-config.yaml, expression/collections/frozenlist.py, expression/collections/seq.py, expression/core/aiotools.py, expression/core/misc.py, tests/test_frozenlist.py, tests/test_seq.py
- Add seq delay, mapi, append operators
- Add list mapi operator
- Upgrade pyright to 1.1.104
- Rename `run_synchronous` to `run_synchronously` to match F# `runSynchronously`
- Fix type annotations in async module (aiotools)
=> Add mapi, append and delay for Seq and FrozenList

expression/core/option.py
`Some(42).or_else(f())` evaluates f() even though the result is never applied, and this is what you do not like when f() performs heavy computations. `Some(42).or_else_with(lambda: f())` is the solution to this problem.
https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-optionmodule.html#orElseWith
=> Add or_else_with

expression/system/disposable.py
Just came across this typo whilst reading the docs.
=> Fix typo: dispoose -> dispose

.pre-commit-config.yaml, expression/collections/asyncseq.py, expression/collections/frozenlist.py, expression/collections/map.py, expression/collections/seq.py, expression/core/aiotools.py, expression/core/choice.py, expression/core/option.py, expression/core/result.py, expression/system/error.py, pyrightconfig.json, tests/test_catch.py, tests/test_frozenlist.py, tests/test_seq.py
- Upgrade Pyright to 1.1.158
- Typing cleanup (no need for typing protocols, finally)
=> Pyright upgrade

expression/collections/frozenlist.py, tests/test_frozenlist.py
Fixes typing errors in #39 by only allowing sort on a sortable list (i.e where the elements supports less-than operator)
=> Fix typing errors in #39

expression/__init__.py, expression/collections/block.py, expression/core/__init__.py, expression/core/curry.py, tests/test_curried.py
Rename `curry_flipped` to the shorter `curry_flip` that is also closer to the `flip` function that inspired its name.
=> feat: rename curry_flipped to curry_flip

README.md
According to https://github.com/cognitedata/Expression/pull/84
I assume this has been an oversight, when removing the old pattern matching and its references.
Thanks for your work!
=> Remove reference to old pattern matching

expression/collections/seq.py, tests/test_seq.py
Make sure we don't consume all of the iterable when only taking n items
=> Make sure seq take is lazy

expression/collections/array.py
The print here seems to be accidentally committed in code for debugging?
=> Remove print at __len__ and __eq__ of TypedArray

docs/tutorial/introduction.md
It had:
```
let compose(f: Callable[[A], B], g: Callable[[B], C]) -> Callable[[A], C]:
lambda x: g(f(x))
```
And should have been:
```
def compose(f: Callable[[A], B], g: Callable[[B], C]) -> Callable[[A], C]:
return lambda x: g(f(x))
```
=> Fix python error in introduction.md

expression/core/option.py, expression/core/result.py, tests/test_option.py, tests/test_result.py
* Convert `Option`s to `Result`s and vice versa
* Added `Option#to_optional` for easy convertion to Python's `Optional[T]`
* Added a `Result#swap` method
* Added tests for all of the above
Also:
* Fixed some documentation for `Result#default_values` and `Result#default_with`
=> Added some methods and functions to `option` and `result`

README.md, pyproject.toml
1. Changed mentions of python 3.9 to python 3.11
2. Added an example of applicative for options in reference to [issue-145](https://github.com/dbrattli/Expression/issues/145)
=> Update README and mentions of python 3.9 to python 3.11

expression/collections/block.py, expression/core/compose.py, expression/core/misc.py, expression/core/option.py, expression/core/pipe.py, tests/test_option.py, tests/test_pipe.py, tests/test_result.py, tests/test_seq.py, tests/test_try.py
- Add `starcompose`
- Fixes typing and handling of `starpipe`
- Adds `starmap` to option
Fixes #185
=> fix: starpipe bugfix and type hints

expression/core/compose.py
Ref: https://github.com/microsoft/pyright/pull/7917#event-12808475540
=> Fix compose type annotation and add docstring

expression/collections/asyncseq.py
The `itertools.repeat` accepts negative or positive numbers, but not null values.
=> fix: null times to 0

.pre-commit-config.yaml, expression/collections/array.py, expression/collections/map.py, expression/core/tagged_union.py, expression/core/typing.py, expression/extra/parser.py
Starting with `pyright>=1.1.374`, a big change to `TypeVar` has been announced,
which is said to fix a number of errors reported over the past year.
This allowed us to remove some of the old `type: ignore`.
see more: https://github.com/microsoft/pyright/releases/tag/1.1.374
=> chore: update pyright

.github/workflows/python-package.yml, expression/collections/block.py, expression/core/compose.py, expression/core/misc.py, expression/core/option.py, expression/core/pipe.py, expression/core/tagged_union.py, poetry.lock, pyproject.toml, pyrightconfig.json
related: #216 
The `match ~ case` syntax is available in `python>=3.10`. 
`TypeVarTuple` and `dataclass_transform` can be supported by `typing_extensions` included in the dependency.
Additionally, I fixed the syntax sugar for `Unpack`.
=> Feat support py310

expression/core/result.py, tests/test_result.py
Also:
* `is_ok` and `is_error` use a comparison instead of a match as the comparison is faster
* Fixed a typo
=> Added Result merge method

expression/core/result.py, tests/test_result.py
Also:
* Added pipeable functions for some methods that were missing them
* Added tests for `Result#map_error`
* Added tests for piping functions
=> Added Result filter methods

README.md, expression/core/curry.py
Make sure we propagate function docstrings through the `curry` and `curry_flip` wrappers
=> Fix curried function docstrings
